# Generated by Django 4.2.1 on 2023-05-21 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buku.kategori'),
        ),
    ]
