# Generated by Django 4.2.1 on 2023-05-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
